In [4]:
# import necessary library
import numpy as np
import pandas as pd
from sklearn import linear_model 

In [7]:
# import dataframe
df = pd.read_csv("C:\\Users\\NTS-PratikshaSarole\\Downloads\\linear regreesion using single variable\\home_price_prediction\\homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [8]:
# creating training model
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [11]:
model.coef_

array([135.78767123])

In [12]:
model.intercept_

180616.43835616432

In [14]:
# predict price
model.predict([[5000]])

C:\Users\NTS-PratikshaSarole\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [15]:
# pickel model
import pickle

In [16]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [17]:
#get location of model-pickle file
import os
os.getcwd()

'C:\\Users\\NTS-PratikshaSarole'

In [18]:
# read model_pickle file
with open('model_pickle','rb') as f:
    mp = model = pickle.load(f)


In [19]:
mp.predict([[5000]])

C:\Users\NTS-PratikshaSarole\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [25]:
# save model using sklearns joblib method
# import sklearn module
import joblib
 


In [26]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [28]:
# load model
mj = joblib.load('model_joblib')
mj

LinearRegression()

In [29]:
mj.predict([[5000]])


C:\Users\NTS-PratikshaSarole\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [30]:
mj.coef_

array([135.78767123])